@startuml
left to right direction
skinparam backgroundColor white
skinparam shadowing false
skinparam class {
  BorderColor black
  BackgroundColor white
}

class User {
  +id: bigint <<PK>>
  +username: string(150)
  +password: string(128)
  +email: string(254)
  +first_name: string(150)
  +last_name: string(150)
  +photo: image [0..1]
  +is_staff: boolean
  +is_active: boolean
  +date_joined: datetime
}

class Category {
  +id: bigint <<PK>>
  +name: string(100) <<unique>>
  +cost: integer
}

class Task {
  +id: bigint <<PK>>
  +spent: integer [1..24]
  +time_create: datetime
  +comment: string(1000)
  +report: file [0..1]
}

User "1" --o "0..*" Task : worker >
Category "1" --o "0..*" Task : category >

@enduml
